# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L6Lva_GP-3w1J3eugNk7zKt_A4G4V4ho
"""

# Sample data structures to store user and e-waste information
users = []
ewaste_items = []
recycling_info = []

# User Registration and Login
def register(username, password):
    for user in users:
        if user['username'] == username:
            print("Username already exists!")
            return
    users.append({'username': username, 'password': password})
    print("User registered successfully!")

def login(username, password):
    for user in users:
        if user['username'] == username and user['password'] == password:
            print("Login successful!")
            return username
    print("Login failed!")
    return None

# E-waste Collection
def add_ewaste(username, item_name, item_description, quantity):
    ewaste_items.append({
        'organization': username,
        'item_name': item_name,
        'item_description': item_description,
        'quantity': quantity,
        'status': 'Pending'
    })
    print("E-waste item added successfully!")

# View E-waste
def view_ewaste(username):
    for item in ewaste_items:
        if item['organization'] == username:
            print(f"Item: {item['item_name']}, Description: {item['item_description']}, "
                  f"Quantity: {item['quantity']}, Status: {item['status']}")

# Update E-waste Status
def update_ewaste_status(item_name, new_status):
    for item in ewaste_items:
        if item['item_name'] == item_name:
            item['status'] = new_status
            print(f"E-waste status updated to {new_status} for item: {item_name}")
            return
    print("Item not found!")

# Recycling Process
def add_recycling(item_name, recycling_status):
    for item in ewaste_items:
        if item['item_name'] == item_name:
            recycling_info.append({
                'item_name': item_name,
                'recycling_status': recycling_status
            })
            item['status'] = 'Recycled'
            print(f"Recycling process recorded for item: {item_name}")
            return
    print("Item not found!")

# Generate Report
def generate_report():
    print("E-waste Report:")
    for item in ewaste_items:
        recycling_status = next((r['recycling_status'] for r in recycling_info if r['item_name'] == item['item_name']), "Not Recycled")
        print(f"Organization: {item['organization']}, Item: {item['item_name']}, "
              f"Quantity: {item['quantity']}, Status: {item['status']}, Recycling Status: {recycling_status}")

# Main Program Flow
def main():
    while True:
        print("\n1. Register")
        print("2. Login")
        print("3. Exit")
        choice = input("Enter choice: ")

        if choice == '1':
            username = input("Enter username: ")
            password = input("Enter password: ")
            register(username, password)

        elif choice == '2':
            username = input("Enter username: ")
            password = input("Enter password: ")
            logged_in_user = login(username, password)
            if logged_in_user:
                while True:
                    print("\n1. Add E-waste")
                    print("2. View E-waste")
                    print("3. Update E-waste Status")
                    print("4. Add Recycling Info")
                    print("5. Generate Report")
                    print("6. Logout")
                    user_choice = input("Enter choice: ")

                    if user_choice == '1':
                        item_name = input("Enter item name: ")
                        item_description = input("Enter item description: ")
                        quantity = int(input("Enter quantity: "))
                        add_ewaste(logged_in_user, item_name, item_description, quantity)

                    elif user_choice == '2':
                        view_ewaste(logged_in_user)

                    elif user_choice == '3':
                        item_name = input("Enter item name to update: ")
                        status = input("Enter new status (Pending/Collected/Recycled): ")
                        update_ewaste_status(item_name, status)

                    elif user_choice == '4':
                        item_name = input("Enter item name for recycling: ")
                        recycling_status = input("Enter recycling status: ")
                        add_recycling(item_name, recycling_status)

                    elif user_choice == '5':
                        generate_report()

                    elif user_choice == '6':
                        break

        elif choice == '3':
            break

if __name__ == '__main__':
    main()
# Sample data structures to store user and e-waste information
users = []
ewaste_items = []
recycling_info = []

# User Registration and Login
def register(username, password):
    for user in users:
        if user['username'] == username:
            print("Username already exists!")
            return
    users.append({'username': username, 'password': password})
    print("User registered successfully!")

def login(username, password):
    for user in users:
        if user['username'] == username and user['password'] == password:
            print("Login successful!")
            return username
    print("Login failed!")
    return None

# E-waste Collection
def add_ewaste(username, item_name, item_description, quantity):
    ewaste_items.append({
        'organization': username,
        'item_name': item_name,
        'item_description': item_description,
        'quantity': quantity,
        'status': 'Pending'
    })
    print("E-waste item added successfully!")

# View E-waste
def view_ewaste(username):
    for item in ewaste_items:
        if item['organization'] == username:
            print(f"Item: {item['item_name']}, Description: {item['item_description']}, "
                  f"Quantity: {item['quantity']}, Status: {item['status']}")

# Update E-waste Status
def update_ewaste_status(item_name, new_status):
    for item in ewaste_items:
        if item['item_name'] == item_name:
            item['status'] = new_status
            print(f"E-waste status updated to {new_status} for item: {item_name}")
            return
    print("Item not found!")

# Recycling Process
def add_recycling(item_name, recycling_status):
    for item in ewaste_items:
        if item['item_name'] == item_name:
            recycling_info.append({
                'item_name': item_name,
                'recycling_status': recycling_status
            })
            item['status'] = 'Recycled'
            print(f"Recycling process recorded for item: {item_name}")
            return
    print("Item not found!")

# Generate Report
def generate_report():
    print("E-waste Report:")
    for item in ewaste_items:
        recycling_status = next((r['recycling_status'] for r in recycling_info if r['item_name'] == item['item_name']), "Not Recycled")
        print(f"Organization: {item['organization']}, Item: {item['item_name']}, "
              f"Quantity: {item['quantity']}, Status: {item['status']}, Recycling Status: {recycling_status}")

# Main Program Flow
def main():
    while True:
        print("\n1. Register")
        print("2. Login")
        print("3. Exit")
        choice = input("Enter choice: ")

        if choice == '1':
            username = input("Enter username: ")
            password = input("Enter password: ")
            register(username, password)

        elif choice == '2':
            username = input("Enter username: ")
            password = input("Enter password: ")
            logged_in_user = login(username, password)
            if logged_in_user:
                while True:
                    print("\n1. Add E-waste")
                    print("2. View E-waste")
                    print("3. Update E-waste Status")
                    print("4. Add Recycling Info")
                    print("5. Generate Report")
                    print("6. Logout")
                    user_choice = input("Enter choice: ")

                    if user_choice == '1':
                        item_name = input("Enter item name: ")
                        item_description = input("Enter item description: ")
                        quantity = int(input("Enter quantity: "))
                        add_ewaste(logged_in_user, item_name, item_description, quantity)

                    elif user_choice == '2':
                        view_ewaste(logged_in_user)

                    elif user_choice == '3':
                        item_name = input("Enter item name to update: ")
                        status = input("Enter new status (Pending/Collected/Recycled): ")
                        update_ewaste_status(item_name, status)

                    elif user_choice == '4':
                        item_name = input("Enter item name for recycling: ")
                        recycling_status = input("Enter recycling status: ")
                        add_recycling(item_name, recycling_status)

                    elif user_choice == '5':
                        generate_report()

                    elif user_choice == '6':
                        break

        elif choice == '3':
            break

if __name__ == '__main__':
    main()